# Generated by Django 4.2 on 2025-01-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuenly',
            fields=[
                ('id_frecuenly', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id_database', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=5432)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('database_name', models.CharField(max_length=100)),
                ('id_frecuenly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Databases.frecuenly')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Databases.type')),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('date_init', models.DateTimeField(auto_now=True)),
                ('date_finishing', models.DateField()),
                ('location', models.URLField()),
                ('state', models.CharField(max_length=10)),
                ('id_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Databases.databases')),
            ],
        ),
    ]
