# Generated by Django 5.1.5 on 2025-04-22 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id_database', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=5432)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id_frecuenly', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('date_init', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_finishing', models.DateTimeField(null=True)),
                ('location', models.URLField()),
                ('state', models.IntegerField(choices=[(0, 'FAILED'), (1, 'PENDING'), (2, 'SUCCESSFUL'), (3, 'IN_PROCESS')], default=1)),
                ('id_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Databases.database')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='id_frecuenly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Databases.frequency'),
        ),
        migrations.AddField(
            model_name='database',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Databases.type'),
        ),
    ]
