# Generated by Django 5.1.5 on 2025-04-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
