# Generated by Django 4.2 on 2025-01-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Databases',
            new_name='Database',
        ),
        migrations.RenameModel(
            old_name='Frecuenly',
            new_name='Frequency',
        ),
    ]
