# Generated by Django 4.2 on 2025-01-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0002_rename_databases_database_rename_frecuenly_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='database_name',
        ),
    ]
