# Generated by Django 5.1.5 on 2025-04-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0002_alter_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
