# Generated by Django 4.2 on 2025-01-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0003_remove_database_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date_finishing',
            field=models.DateField(null=True),
        ),
    ]
