# Generated by Django 5.1.5 on 2025-04-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0004_alter_database_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='id_user',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
