# Generated by Django 4.2 on 2025-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0004_alter_backup_date_finishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date_finishing',
            field=models.DateTimeField(null=True),
        ),
    ]
