# Generated by Django 5.1.5 on 2025-04-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0005_alter_backup_date_finishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='location',
            field=models.URLField(default='C:\\Users\\Fer\\Desktop\\Databases Backup System\\Backend\\backups'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='state',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
