# Generated by Django 5.1.5 on 2025-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0005_alter_database_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
