# Generated by Django 5.1.5 on 2025-04-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0006_alter_backup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
