# Generated by Django 5.1.5 on 2025-04-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0006_database_location_alter_backup_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='location',
        ),
    ]
