# Generated by Django 5.1.5 on 2025-04-21 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0007_remove_database_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 23, 43, 55, 838318, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='backup',
            name='state',
            field=models.IntegerField(choices=[(0, 'FAILED'), (1, 'PENDING'), (2, 'SUCCESSFUL')], default=1),
        ),
    ]
