# Generated by Django 5.1.5 on 2025-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0007_alter_backup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='id_user',
            field=models.CharField(default=1, max_length=500),
        ),
    ]
