# Generated by Django 5.1.5 on 2025-04-22 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0008_alter_backup_date_init_alter_backup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 7, 24, 39, 606680, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='backup',
            name='state',
            field=models.IntegerField(choices=[(0, 'FAILED'), (1, 'PENDING'), (2, 'SUCCESSFUL'), (3, 'IN_PROCESS')], default=1),
        ),
    ]
