# Generated by Django 5.1.5 on 2025-04-22 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0009_alter_backup_date_init_alter_backup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date_init',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 7, 28, 57, 525912, tzinfo=datetime.timezone.utc)),
        ),
    ]
