# Generated by Django 5.1.5 on 2025-04-22 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Databases', '0010_alter_backup_date_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='date_init',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
